### ISSUE TITLE
One General question.

### ISSUE THREAD

**Issue by ghost** [tdonohue/DSpace-Spring-Boot#1]
Hi @tdonohue,

```
 I have a question regarding the DSpace-Spring-Boot. At least to me is hard to see what is the point of use spring boot here, because everything else in the space still in the "old tomcat war" style. Are you thinking about to use the provide the all Dspace modules as a micro-service? I am asking it because it is the way that it makes sense to me, each one of the modules, your jar micro service. Otherwise is simpler to use Spring MVC, thymeleaf and DSpace-API as the frameworks to the new ui, right?
```

Best Regards
Luiz

**Comment by tdonohue** [comment]
One of the immediate benefits of Spring Boot  over Spring MVC in this scenario is the ability to immediately create a "runnable WAR" (with Tomcat embedded).  This prototype creates a WAR that is executable (no need to install Tomcat). 

Spring Boot also requires a lot less Spring configuration than straight MVC. Running this prototype on Spring Boot allowed me to get started much more quickly as it auto-discovered all of our Spring beans.

In the situation of this protoype, you are correct, I haven't done a ton in Spring Boot that couldn't also be done in Spring MVC.  Since Spring Boot is really just a wrapper around Spring MVC which makes it easier to run web applications, the goal of this prototype was just to get my feet wet with Spring Boot.  

If we were to decide to go with Spring Boot longer term, I think we'd likely want to determine whether DSpace could become a single webapp (which is not just the main UI, but also OAI, SWORD, REST, etc) which can be packaged up into a runnable WAR via Spring Boot. This prototype didn't investigate the feasibility of that however, as we were limited to 80 hours or less of work.

**Comment by ghost** [comment]
Ok, I got it, thanks. I liked the way that you used DSpace-api in the controllers. Another question, in the readme you said (Dspace pre-6) and then you said it doesn't work in with DSpace 5 because the changes in the API, I got the changes part, but I got confusing, it should run in a Dspace 6 installation as a "background", right?

Thanks
Luiz

**Comment by tdonohue** [comment]
Yes, currently, since this Prototype does not have the ability to _create_ content (Communities, Collections or Items), you need to point it at an existing installation of DSpace (mainly an existing database with content already in it).  That existing installation needs to be a pre-6 installation, as this prototype uses the DSpace 6 API (which is significantly changed).

That does mean this prototype is slightly more painful to work with if you don't have a DSpace pre-6 install.

Basically, you'd just:
- Checkout the 'master' branch of DSpace from: https://github.com/DSpace/DSpace/ (this is pre-6).
- Install it by running "mvn clean package; ant fresh_install" (of course you need to setup a database for it to install into, and select an installation directory, just like you would in any old version of DSpace)
- Add some content to it, using the existing XMLUI or JSPUI
- Then install the prototype, and point it at the same DSpace installation directory. It'll be able to allow you to view/browse the existing content, etc. There's more info on what it can / cannot do in the README

This prototype, like all other prototype UIs, is really just a way to "play with" a given set of technologies (in this case, Spring Boot  + Thymeleaf). None of the prototypes are very fully featured, so this is obviously not a full UI. But it is a proof of concept and shows that there's the potential to use Spring Boot + Thymeleaf to build the next UI.
