### ISSUE TITLE
build properties

### ISSUE THREAD

**Issue by ghost** [tdonohue/DSpace-Spring-Boot#2]
Hi Tim,

```
One think that I realized, the file build.properties is missing.
I am using Intellij to run it and I got the error below, it seems like it did not found applications.properties dspace.dir. I put the file in the dspace-ui/main/resources folder, because I doing it in the IDE, do you have any idea why it is not working? Maybe I'm missing something.
```

```
2016-01-26 16:43:52.818  INFO 2246 --- [ost-startStop-1] o.d.servicemanager.DSpaceKernelInit      : Created new kernel: DSpaceKernel:org.dspace:name=f123740b-b68e-4668-bc1c-2ddad2d1e219,type=DSpaceKernel:lastLoad=null:loadTime=0:running=false:kernel=null
Failure during filter init: DSpace home directory could not be determined. It MUST include a subpath of '/config/config-definition.xml'. Please consider setting the 'dspace.dir' system property or ensure the dspace-api.jar is being run from [dspace]/lib/.:java.lang.RuntimeException: DSpace home directory could not be determined. It MUST include a subpath of '/config/config-definition.xml'. Please consider setting the 'dspace.dir' system property or ensure the dspace-api.jar is being run from [dspace]/lib/.
2016-01-26 16:43:52.828 ERROR 2246 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener

java.lang.RuntimeException: Failure during filter init: DSpace home directory could not be determined. It MUST include a subpath of '/config/config-definition.xml'. Please consider setting the 'dspace.dir' system property or ensure the dspace-api.jar is being run from [dspace]/lib/.
```

**Comment by tdonohue** [comment]
Hi @LuizClaudioSantos , sorry for the delayed response. I forgot about this question.

The problem you are seeing is that this prototype uses the DSpace 6 API, and DSpace 6 has an [Enhanced Configuration Scheme](https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme).  The old `build.properties` file has been replaced with a new configuration file named `local.cfg`.  There's a `[src]/local.cfg.EXAMPLE` now that provides a sample `local.cfg` file.

The full, changed instructions for how to build/install DSpace 6 with this new configuration scheme are at: https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme#EnhancedConfigurationScheme-Building/InstallingDSpace

So, in order to use this prototype, you'd want to create your own `local.cfg` file, and ensure the `dspace.dir` setting in that file points at your DSpace installation directory.  Much more detailed info on the `local.cfg` file and its usage are in the docs linked above.
